### ISSUE TITLE
Deleting rows or columns in-place does not work, i.e. deleteat!, pop!, splice!

### ISSUE THREAD

**Issue by jlambvo** [davidavdav/NamedArrays.jl#135]
Is there any method to delete a row/column by name? Methods for other types of collections do not appear to work. Seems related to #89.

**Comment by davidavdav** [comment]
You can use `Not(index)` as index, and re-assign if you wish:
```julia
n = NamedArray(randn(2, 3), (["a", "b"], ["a", "b", "c"]))
n = n[:, Not("b")]
```
