### ISSUE TITLE
Feature request? Indexing when order of dimensions is not known

### ISSUE THREAD

**Issue by kjowens** [davidavdav/NamedArrays.jl#15]
Sorry if this isn't the right place to ask about this.

This package is pretty cool, but one thing I couldn't figure out from reading the documentation is if it is possible to index when the order of dimensions is unkown at compile time. For example, say I'm working on a project and I want to set it up as "struc of arrays" rather than "array of strucs". So, I would have several multi-dimensional arrays. I would want to write a library that would let the user define the dimensions of arrays based on their input data. Or, I might want to experiment with different dimension orders. Or, I might just forget if I haven't been working on the project for a while.

So, would it be possbile to make a method with an extra flag or type to signal un-ordered dimensions? It would need to add an intermediate layer to look-up each demension's order, then re-order the indexing conditions. Maybe a macro would be best?

**Comment by davidavdav** [comment]
Hi, 

Sorry, I had somehow missed this.  

Do you want a permutation of the dimensions afterwards?   There is `permutedims!()`, bit that looks rather awkward to use.

**Comment by kjowens** [comment]
No, that wouldn't be necessary. It would be for a situation where the user
of a library forgets the order of dimensions.

**Comment by davidavdav** [comment]
So would you like to have keyword arguments for the `[]` operator, like `a[B="yes", A="five"]`?

**Comment by kjowens** [comment]
Yes, though I'm not sure how you'd implement it. It might be better to have
a function take a Dict as an argument, where the keys are the dimension
names and the values are the indexes for each dimension. then, in the named
array type have some way to look-up the order of an index name. the two
dictionaries could match on key, sort by dimension order index, and then
it's a matter formatting it to lookup in the normal way. maybe it would
need a macro since you'd be writing an expression?

i just think it would make the package easier to use when you have 3+
dimensions with multiple arrays, and the arrays have different dimensions.

a simplified example: say you have these arrays

store X customer

store X product

customer X product

you'd either have to remember the order or look it up each time you want to
do something new. i hope that makes sense.

**Comment by nalimilan** [comment]
It would be interesting to have a look at how AxisArrays.jl does this.

**Comment by davidavdav** [comment]
Along the lines of AxisArrays, the syntax would be something like `a[Name{:B}("yes"),Name{:A}("five")]`.  I don't think that makes things more clear.  The dict is a good suggestion, but the shorthand `{:B=>"yes", :A=>"five"}` has been deprecated.  Your last suggestion, using macros, might be the way to go.  However, macros make me very uncomfortable.  

I just found out that a `Pair` may be way to go.  I'll have a look at that now.  Yes.  I can use the `a[:B=>"yes", :A=>"five"]` syntax without macros.
