### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by cstjean** [davidavdav/NamedArrays.jl#16]
I expected matrix multiplication to try to align matrices together before performing multiplication, but it doesn't. I wouldn't mind writing that code, if it's decided that it's the correct behavior.

```julia
x = NamedArray(Int[1 3; 2 4], ( ["A","B"], ["C","D"] ))
y = NamedArray(Int[1 3; 2 4], ( ["A","B"], ["D","C"] ))  # flipped D and C

> x * x   # I expected an error
A \ B C  D 
A     7  15
B     10 22

> x * x'  # this is correct
A \ A A  B 
A     10 14
B     14 20

> x * y'   # this isn't
A \ A A  B 
A     10 14
B     14 20 
```

**Comment by davidavdav** [comment]
Hi, 

Thanks for the comment.  In the README, it says something like "and perhaps even some sort of dimension-checking in certain matrix computations".  Clearly this hasn't been implemented yet, and your proposal goes even further: to actually *use* the names of the indices to figure out which indices should be combined.  I like that. 

While we're at it, we can use the dimnames to figure out the dimension over which the reduction takes place.  E.g., matrix A(with dimnames [:a, :b]) * B(with dimnames [:a, :c]) = A' *  B (with dimnames [:b ,:c])

Sure, if you want to write that code, please do so.  

I don't think many people actually use NamedArrays, despite all my efforts to define all matrix operations.  So we still have the freedom to define powerful semantics.  Think of the inner product of to NamedVectors that sums over shared indices.

**Comment by cstjean** [comment]
Hi, thank you for the response, this slipped under my radar for a while. What I would really like is for Pandas-like dataframe support, and NamedArrays already brings us part of the way there. It's good to know that we have the flexibility of changing semantics still. I'm waiting for the Julia-Stats masterplan to be published before deciding where to invest my efforts.

**Comment by davidavdav** [comment]
OK, good luck with waiting for Julia-Stats to make up their mind.  I've been waiting for the decision for how an R `table()` function (imho the most useful function in R) should be called, along with a good implementation.  

NamedArrays may help in storing the result of such a table.  However, nobody seems interested in named arrays.

**Comment by nalimilan** [comment]
@davidavdav You're aware of my https://github.com/nalimilan/FreqTables.jl package, right? If think we should develop the implementation there, and it will eventually move to StatsBase if it becomes the standard.

**Comment by davidavdav** [comment]
Hi Milan, 

No, I wasn't.  I did have an earlier version about tables from you checked out, but that was about a year ago.  It looks nice from the description.  Hope it will end up in JuliaStats. 

Thanks, 

---david

**Comment by nalimilan** [comment]
I think we need to settle on a common design for NamedArrays/AxisArrays before anything in StatsBase can depend on this kind of feature.

**Comment by davidavdav** [comment]
Cool package, AxisArray.  But afai can see, not really a replacement for NamedArrays.

**Comment by datnamer** [comment]
@cstjean  http://juliacomputing.com/blog/2016/01/14/stats-roadmap.html

**Comment by davidavdav** [comment]
Thanks.  That is recent!

**Comment by davidavdav** [comment]
Hi, 

would https://github.com/Jutho/TensorOperations.jl do the job for you?  Here naming and matching is all carried out in a macro, I believe.

**Comment by cstjean** [comment]
Potentially, and thank you for the link, but I'm not working on that problem anymore. We can close this issue if you'd like. 

BTW, there was a big pow-wow on dataframe-like-objects today at JuliaCon. I missed it, but it seems that people will start working on a shared interface (in AbstractTables.jl?)

**Comment by davidavdav** [comment]
OK, thanks, I'll close this then.
