### ISSUE TITLE
Simplify printing type

### ISSUE THREAD

**Issue by nalimilan** [davidavdav/NamedArrays.jl#18]
I find the current way of printing the full type of the array quite verbose, e.g.:
```julia
2x2 NamedArray{Int64,2,Array{Int64,2},Tuple{Dict{ASCIIString,Int64},Dict{Bool,Int64}}}
Species \ LongSepal false true 
setosa              28    22   
versicolor          3     8  
```

What do you think about printing only the first part of the type? I.e.:
```julia
2x2 NamedArray{Int64,2,...}
```

**Comment by davidavdav** [comment]
Yes, I agree.  I generally find these type specifications quite verbose.  I think that for printing I just use the default type printing in Julia.
