### ISSUE TITLE
OrderedDict for names?

### ISSUE THREAD

**Issue by phaverty** [davidavdav/NamedArrays.jl#19]
The OrderedDict type from DataStructures.jl might be a nice data structure to hold the names. OrderedDict will soon be based on a speedy implementation by Jeff Bezanson. OrderedSet might also be appropriate.

**Comment by davidavdav** [comment]
Yes, thanks, this is a good suggestion.  I didn't know ordereddict was around.

**Comment by davidavdav** [comment]
Is OrderedDict faster than Dict?

**Comment by nalimilan** [comment]
I don't think it is, though I think Jeff's implementation is quite fast (i.e. more or less as fast as `Dict`). If it were faster, `Dict` could be implemented using `OrderedDict`.

**Comment by phaverty** [comment]
I got the idea from this pull request:
https://github.com/JuliaLang/julia/pull/10116
It is faster for certain things. It seems that it was considered for use in
base julia, but discussion is ongoing.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
Resolved by PR #31
