### ISSUE TITLE
Support 0-dimensional arrays

### ISSUE THREAD

**Issue by nalimilan** [davidavdav/NamedArrays.jl#21]
Named 0-dimensional arrays are certainly not really useful in themselves, but they can arise as special cases of more general functions. For example, I would find it useful for a frequency table with no variables (which would return the number of cases) in FreqTables.jl.

Currently, they are not supported, as the constructor returns the scalar `0`:
```julia
julia> NamedArray(Array{Int}())
0
```

According to `@which NamedArray(Array{Int}(), (), ())`, this is because of a method apparently defined merely to prevent ambiguity warnings. Do you think it would be possible to fix this? At the very least, it should raise an error, instead of an incorrect result.

**Comment by davidavdav** [comment]
Yes, it is certainly possible I put in the constructor to deal with an ambiguity warning.  These I find one of the most difficult things to deal with properly.  Usually, for every ambiguity case I deal with, I get several new ones back.  E.g, loading both NamedArrays and DataFrames results in millions of ambiguity errors, I don't even want to start thinking about that. 

Il looks like I didn't know how to activate the ambiguity in the first place, so the answer `0` was there to trigger a warning.  Which, by means of #21, it finally did.

**Comment by davidavdav** [comment]
If this this fixes your problem, I'll submit a new PR to METADATA.

**Comment by nalimilan** [comment]
Thanks, that fixed it. Though there's still a small glitch in the printing:
```julia
julia> NamedArray(Array{Int}())
 NamedArray{Int64,0}
140527034957824
```

Notice the leading space. Standard `Array` seems to have a special case for it, since it prints `0-dimensional Array` instead of the actual dimensions.

**Comment by nalimilan** [comment]
FWIW, Julia Base uses this:
```julia
dims2string(d) = isempty(d) ? "0-dimensional" :
                 length(d) == 1 ? "$(d[1])-element" :
                 join(map(string,d), 'x')
```

**Comment by nalimilan** [comment]
BTW, I don't think automatically adding the `Named` prefix to the wrapped array type is a good idea. It will often print a type that doesn't exist. Maybe better print `NamedArray{$(typeof(a.array))}`, even if that's not technically 100% correct.
