### ISSUE TITLE
adding reverse option in the sort function

### ISSUE THREAD

**Issue by youngjaewoo** [davidavdav/NamedArrays.jl#26]
Hello, Just trying out NamedArrays with FreqTables. It would be great to have "rev" function added into the sort function. Doesn't fully understand how NamesArray works, but would something like this work from what you already have?

`function sort(a::NamedVector, rev=false)`
    `i = sortperm(a.array, rev)`
    `return NamedArray(a.array[i], (names(a, 1)[i],), a.dimnames)`
`end`

**Comment by davidavdav** [comment]
OK, sorry, I didn't know `sort()` had keywords. 

I found that `sort!(::NamedArray)` was also missing.  

For `ndims()>1`, `sort!()` is difficult to define for a  `NamedArray`.  So there is only `sort()` that re-numbers along the sorted dimension (each column/row/... is sorted individually).  This may change the name type along that dimension, and therefore change the type of the `NamedArray`.  That can't happen.
