### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by nalimilan** [davidavdav/NamedArrays.jl#28]
The last release currently fails on Julia 0.5:
http://pkg.julialang.org/logs/NamedArrays_0.5.log

OTC, git master seems to work (modulo two warnings). Given that people are going to try testing Julia 0.5 and porting their packages to it, could you tag a new release of NamedArrays? Thanks.

**Comment by davidavdav** [comment]
Yes, i already prepared a new release. The latest om github should pass
0.5. I had to let go of 0.3.

---david

sent from a mobile Linux os.

**Comment by nalimilan** [comment]
What do you mean by "prepared"? On GitHub, the latest release is 0.4.8, which AFAICT has test errors.

**Comment by davidavdav** [comment]
Sorry I meant the [commit](https://github.com/davidavdav/NamedArrays.jl/commit/ccf26532c48e5175d6ec2ffaa93c308493ddf476).  I now submitted a metadata pull request.
