### ISSUE TITLE
(Pretty) print arrays with second dimension of size 1

### ISSUE THREAD

**Issue by compleconomics** [davidavdav/NamedArrays.jl#33]
Thank you very much for fixing #32. The following problem is most likely closely related to this. 

Printing simple two-dimensional Named Arrays like
`NamedArray(rand(Int16,1,2))`
`NamedArray(rand(Int16,2,1))`
works nicely.

However whenever a third or generally higher order dimensions are added, the case of the second dimension having size 1 poses problems. So printing
`NamedArray(rand(Int16,1,2,1))`
works perfectly, but
`NamedArray(rand(Int16,2,1,1))`
does not.

In fact, the error message looks similar to #32 : 

> NamedArray(rand(Int16,2,1,1))
2x1x1 Named Array{Int16,3}
[:, :, C=1] =
Error showing value of type NamedArrays.NamedArray{Int16,3,Array{Int16,3},Tuple{DataStructures.OrderedDict{ASCIIString,Int64},DataStructures.OrderedDict{ASCIIString,Int64},DataStructures.OrderedDict{ASCIIString,Int64}}}:
ERROR: MethodError: `show` has no method matching show(::Base.Terminals.TTYTerminal, ::Array{Int16,2}, ::Int64)
Closest candidates are:
  show(::IO, ::NamedArrays.NamedArray{T,2,AT,DT}, ::Int64)
  show(::IO, ::NamedArrays.NamedArray{T,1,AT,DT}, ::Int64)
  show(::IO, ::AbstractArray{T,N})
  ...
 in show at /Users/lh/.julia/v0.4/NamedArrays/src/show.jl:44
 in writemime at /Users/lh/.julia/v0.4/NamedArrays/src/show.jl:21
 in display at REPL.jl:114
 in display at REPL.jl:117
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:163
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_frontend at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_repl at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib

**Comment by davidavdav** [comment]
Thanks for detecting this.  I suppose the singleton dimensions pose a bit of a problem for a generic approach, I am not a fan of having all kinds of logic for detecting these.  But if there is no other way...

I'll start decoding the error message, which will probably take me some time.
