### ISSUE TITLE
Array labels get lost

### ISSUE THREAD

**Issue by chipkent** [davidavdav/NamedArrays.jl#34]
I'm trying to get my code working with Julia v0.5.0-pre3.  Using this version of Julia, NamedArrays is losing names during some calculations.  The reproducer below and sample output demonstrate the problem.

https://gist.github.com/chipkent/25a5350a5d68fbf6d9795c598b929911

############## Julia 0.4

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> include("scripts/debug/bug_reproducers/named_array_dropped_labels.jl")
DEBUG: factors 1000x5 Named Array{Float64,2}
Time ╲ Factor │   Factor1    Factor2    Factor3    Factor4    Factor5
──────────────┼──────────────────────────────────────────────────────
Time1         │  0.682681   0.641864  0.0604407   0.343892   0.272542
Time2         │   0.85448   0.332101   0.140453   0.306082   0.663562
Time3         │ 0.0672374   0.267711  0.0454517   0.294357   0.749618
Time4         │  0.518892   0.301079   0.890731   0.662586    0.55996
Time5         │ 0.0769554   0.872269   0.442797    0.15841   0.615252
Time6         │  0.885494   0.444591   0.788861   0.717947   0.569386
Time7         │  0.677105   0.137082   0.863631   0.176956   0.166547
Time8         │  0.148325   0.629093   0.925951   0.913291    0.17828
Time9         │  0.944075   0.169607    0.19603   0.379889   0.274374
⋮                       ⋮          ⋮          ⋮          ⋮          ⋮
Time992       │  0.693805   0.383296   0.861673   0.908616     0.1875
Time993       │  0.797499   0.963533   0.423591    0.44484    0.64167
Time994       │  0.951585   0.969613   0.312815   0.966057   0.124742
Time995       │  0.852963   0.630625   0.317665  0.0637761   0.972642
Time996       │  0.753594   0.457059   0.905828   0.604936   0.147711
Time997       │  0.860515   0.226983   0.221333  0.0654931   0.150316
Time998       │  0.896473   0.682781  0.0473148   0.190468   0.343856
Time999       │  0.788534   0.732614    0.80583   0.738317  0.0428651
Time1000      │  0.154106   0.132844   0.990082   0.731786   0.941636
DEBUG: returns 1000x100 Named Array{Float64,2}
Time ╲ Security │        Sec1         Sec2  …        Sec99       Sec100
────────────────┼──────────────────────────────────────────────────────
Time1           │     0.92638     0.346999  …     0.504168      0.77981
Time2           │    0.902844     0.856281        0.689131     0.751413
Time3           │    0.671873     0.418485        0.406949     0.774751
Time4           │    0.478624     0.661126        0.943033    0.0871396
Time5           │    0.934416     0.940301        0.686554     0.254314
Time6           │    0.186957     0.545432        0.373405     0.467161
Time7           │    0.130868    0.0862504        0.109323    0.0142819
Time8           │    0.445318     0.688901        0.520623     0.673937
Time9           │    0.661327      0.36141        0.870884     0.639285
⋮                           ⋮            ⋮  ⋱            ⋮            ⋮
Time992         │   0.0889218     0.937601        0.654347     0.396031
Time993         │   0.0816654     0.786998        0.671811     0.359932
Time994         │    0.239004     0.652326        0.766721     0.792293
Time995         │    0.763325     0.927483        0.182104      0.97115
Time996         │    0.254187     0.595176        0.309978     0.513739
Time997         │    0.601996     0.265519        0.324926      0.58877
Time998         │    0.318751     0.547839        0.938819     0.273577
Time999         │    0.240346     0.122401        0.662568    0.0681904
Time1000        │    0.158931     0.286803  …     0.871096     0.561676
DEBUG: ff 5x5 Named Array{Float64,2}
Factor ╲ Factor │ Factor1  Factor2  Factor3  Factor4  Factor5
────────────────┼────────────────────────────────────────────
Factor1         │ 324.788   254.07  253.938  243.756  231.664
Factor2         │  254.07  344.417  260.806  251.497  240.182
Factor3         │ 253.938  260.806  353.338  257.702   243.31
Factor4         │ 243.756  251.497  257.702   331.22  239.656
Factor5         │ 231.664  240.182   243.31  239.656  311.273
DEBUG: fr 5x100 Named Array{Float64,2}
Factor ╲ Security │    Sec1     Sec2     Sec3  …    Sec98    Sec99   Sec100
──────────────────┼────────────────────────────────────────────────────────
Factor1           │ 234.794  253.224  249.112  …   250.32  255.091  252.256
Factor2           │ 248.816  264.046  256.174     256.292  265.516  259.334
Factor3           │ 243.699  264.389  261.629     260.414  268.212  266.447
Factor4           │ 236.634  254.935   257.02     241.381  260.939  256.981
Factor5           │  229.31   240.06    242.1  …   232.79  252.774  246.607
DEBUG: result 5x100 Named Array{Float64,2}
Factor ╲ Security │     Sec1      Sec2  …     Sec99    Sec100
──────────────────┼──────────────────────────────────────────
Factor1           │ 0.164591  0.199913  …  0.169594  0.182313
Factor2           │ 0.241299  0.231476     0.194579  0.168288
Factor3           │ 0.145925  0.195515     0.183738  0.208703
Factor4           │ 0.156689   0.18994     0.200051  0.199727
Factor5           │ 0.193295  0.144762  …  0.238063  0.209805
DEBUG: betas 5x100 Named Array{Float64,2}
**Factor ╲ Security │     Sec1      Sec2  …     Sec99    Sec100**
──────────────────┼──────────────────────────────────────────
**Factor1**           │ 0.164591  0.199913  …  0.169594  0.182313
**Factor2**           │ 0.241299  0.231476     0.194579  0.168288
**Factor3**           │ 0.145925  0.195515     0.183738  0.208703
**Factor4**           │ 0.156689   0.18994     0.200051  0.199727
**Factor5**           │ 0.193295  0.144762  …  0.238063  0.209805

############## Julia 0.5

julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

julia> include("scripts/debug/bug_reproducers/named_array_dropped_labels.jl")
INFO: Recompiling stale cache file /cc/home/chip/.julia/lib/v0.5/NamedArrays.ji for module NamedArrays.
DEBUG: factors 1000×5 Named Array{Float64,2}
Time ╲ Factor │   Factor1    Factor2    Factor3    Factor4    Factor5
──────────────┼──────────────────────────────────────────────────────
Time1         │  0.648349   0.855487   0.722463   0.277658   0.132881
Time2         │  0.275969   0.627558    0.51212   0.274781   0.267377
Time3         │   0.24121   0.934418   0.286226   0.234021   0.224865
Time4         │  0.508534   0.241432   0.905717  0.0400031  0.0506311
Time5         │  0.373572   0.640741   0.256917   0.552423   0.747057
Time6         │  0.991241  0.0965737   0.937885   0.235976  0.0370069
Time7         │  0.775712   0.731374   0.910524   0.340915   0.754739
Time8         │  0.692795   0.429867   0.600309   0.437293   0.394104
Time9         │  0.734837   0.560035   0.925546   0.266141   0.336406
⋮                       ⋮          ⋮          ⋮          ⋮          ⋮
Time992       │  0.987371  0.0194012   0.847687   0.952616   0.361282
Time993       │  0.940804   0.722899   0.330103   0.401003   0.130805
Time994       │  0.160483   0.802112   0.984304   0.686892   0.224953
Time995       │  0.553148   0.182517   0.262282   0.365346  0.0556051
Time996       │  0.797495   0.194863   0.122536   0.606609   0.837744
Time997       │  0.694519   0.841973   0.472769   0.184475   0.183813
Time998       │  0.294962   0.153195    0.55467   0.816292   0.565468
Time999       │  0.174693   0.267737   0.949439   0.427911   0.133258
Time1000      │  0.204885   0.590186   0.911271   0.434916   0.654768
DEBUG: returns 1000×100 Named Array{Float64,2}
Time ╲ Security │        Sec1         Sec2  …        Sec99       Sec100
────────────────┼──────────────────────────────────────────────────────
Time1           │    0.961094     0.453677  …      0.70159      0.58722
Time2           │     0.82677     0.948434         0.33833     0.867072
Time3           │    0.397409     0.289738        0.574056      0.19874
Time4           │    0.682279     0.111237        0.728677     0.651904
Time5           │    0.288991     0.755536        0.961669      0.79252
Time6           │    0.417239     0.248621        0.195145     0.518017
Time7           │    0.899178     0.528948        0.696381     0.586146
Time8           │    0.813802     0.203518        0.906128     0.914609
Time9           │    0.811821     0.304146        0.117954      0.57387
⋮                           ⋮            ⋮  ⋱            ⋮            ⋮
Time992         │     0.22345     0.430742        0.117276     0.767789
Time993         │     0.94441     0.105519        0.742508     0.638965
Time994         │    0.972137     0.790848        0.279617      0.26109
Time995         │    0.613253     0.927934        0.875223     0.801898
Time996         │    0.851093     0.297009        0.533278     0.418069
Time997         │    0.929891     0.390823        0.862143     0.852716
Time998         │    0.483609     0.619753       0.0517902    0.0206416
Time999         │    0.840487     0.474191        0.316038     0.907091
Time1000        │    0.523028     0.439595  …     0.968394     0.768594
DEBUG: ff 5×5 Named Array{Float64,2}
A ╲ B │       1        2        3        4        5
──────┼────────────────────────────────────────────
1     │ 332.503  236.967  250.882   251.18  255.296
2     │ 236.967   319.42  243.482  245.373  249.957
3     │ 250.882  243.482  338.008  250.624  254.066
4     │  251.18  245.373  250.624  332.022  251.249
5     │ 255.296  249.957  254.066  251.249   341.92
DEBUG: fr 5×100 Named Array{Float64,2}
A ╲ B │       1        2        3  …       98       99      100
──────┼────────────────────────────────────────────────────────
1     │ 253.242  237.948  251.454  …  256.298  258.981  248.072
2     │ 250.621  236.002  238.929     243.501  248.803  241.593
3     │ 257.734   244.31  251.131     258.019  256.547  248.014
4     │ 253.789  241.661  249.946     259.311  258.438  246.059
5     │ 261.308  249.192  257.263  …  266.681  264.664  255.645
DEBUG: result 5×100 Named Array{Float64,2}
B ╲ B │         1          2          3  …         98         99        100
──────┼────────────────────────────────────────────────────────────────────
1     │  0.172268   0.138416   0.207331  …    0.18332   0.212691   0.192143
2     │  0.211218   0.180836    0.13274      0.106768   0.166369   0.185148
3     │  0.201161   0.193388   0.184974      0.188608   0.163329   0.169682
4     │  0.169127   0.177938    0.18796      0.224197   0.201677   0.160905
5     │  0.207451   0.218805   0.225002  …   0.260134   0.224066   0.224539
DEBUG: betas 5×100 Named Array{Float64,2}
**B ╲ B │         1          2          3  …         98         99        100**
──────┼────────────────────────────────────────────────────────────────────
**1**     │  0.172268   0.138416   0.207331  …    0.18332   0.212691   0.192143
**2**     │  0.211218   0.180836    0.13274      0.106768   0.166369   0.185148
**3**     │  0.201161   0.193388   0.184974      0.188608   0.163329   0.169682
**4**     │  0.169127   0.177938    0.18796      0.224197   0.201677   0.160905
**5**     │  0.207451   0.218805   0.225002  …   0.260134   0.224066   0.224539

**Comment by davidavdav** [comment]
Thanks for the report.  In Julia-0.5 there have been some changes in how the output dimension of slices work.  However, this seem to have to do with matrix arithmetic.

**Comment by davidavdav** [comment]
OK, it seems to have to to with how `x' * y` is processed in Julia-0.5.  In julia-0.4, I could dispatch this by defining `*` for NamedArrays,in julia-0.5 this is dispatched to `At_mul_B` caught by AbstractArray.  I should be able to fix this with a few extra definitions.

**Comment by chipkent** [comment]
Thanks for looking.

**Comment by davidavdav** [comment]
I think I solved the problem, but in testing I ended up in julia-v0.4 ambiguity-hell. Still at it.

**Comment by timholy** [comment]
In case it helps, there's an unfinished blog post on fixing ambiguities [here](https://github.com/JuliaLang/julia/pull/18111).

**Comment by davidavdav** [comment]
Thanks for that.  I think I am in the `AbstractArray` example case you mention, but unfortunately, that all happens in Base so I don't see a way to avoid it, apart from painstakingly adding more specialized functions until the julia-0.4 warnings go away.

**Comment by chipkent** [comment]
Thanks for the fix.  It seems to have resolved all of my problems.
