### ISSUE TITLE
3rd dimension not truncated in pretty print

### ISSUE THREAD

**Issue by marius311** [davidavdav/NamedArrays.jl#36]
Simple request, would it be possible to get the >=3rd dimensions truncated when pretty printed? Otherwise big arrays can hang your REPL / notebook.

**Comment by davidavdav** [comment]
Yes, I saw this coming.  It is pretty hard to compute the number of lines needed for multidimensional, with all kinds of first lines ... last lines shortcuts, etc.  But I'll have a dig at it.

**Comment by marius311** [comment]
Works great, thanks for the quick fix!
