### ISSUE TITLE
Sorting erases indices

### ISSUE THREAD

**Issue by compleconomics** [davidavdav/NamedArrays.jl#42]
Hi, I'm not even sure whether sorting used to work but below you see a minimal example where sorting destroys the indices of the A-dimension (same would hold for B).

Cheers

julia> A = NamedArray([3 4; 1 2])
2x2 Named Array{Int64,2}
A ╲ B │ 1  2
──────┼─────
1     │ 3  4
2     │ 1  2

julia> setnames!(A,["asdf","fdsa"],1)
(DataStructures.OrderedDict("asdf"=>1,"fdsa"=>2),DataStructures.OrderedDict("1"=>1,"2"=>2))

julia> setnames!(A,["hhhh","gggg"],2)
(DataStructures.OrderedDict("asdf"=>1,"fdsa"=>2),DataStructures.OrderedDict("hhhh"=>1,"gggg"=>2))

julia> A
2x2 Named Array{Int64,2}
A ╲ B │ hhhh  gggg
──────┼───────────
asdf  │    3     4
fdsa  │    1     2

julia> sort(A,1)
2x2 Named Array{Int64,2}
A ╲ B │ hhhh  gggg
──────┼───────────
1     │    1     2
2     │    3     4

**Comment by davidavdav** [comment]
If you sort the numbers in dimension 1, by column, the names of dimension 1 cannot be retained.  In your example they can, but this is a coincidence.  

Consider the matrix
```
A = NamedArray([1 2; 4 3], (["a", "b"], ["c", "d"]))
sort(A, 1)
```
You can't retain the original row names in both individually sorted columns.
