### ISSUE TITLE
Second constructor example in README.md fails with a MethodError

### ISSUE THREAD

**Issue by joelgoop** [davidavdav/NamedArrays.jl#46]
The following example of construction of a NamedArray is given in README.md:
```julia
# NamedArray{T}(dims...)
x = NamedArray{Int}(2, 2)
```
However, when I run this, it fails with a MethodError both for the current version on master and for v0.5.3. The fallback constructor in [typedconstructor.jl](https://github.com/davidavdav/NamedArrays.jl/blob/v0.5.3/src/typedconstructor.jl)/[constructors.jl](https://github.com/davidavdav/NamedArrays.jl/blob/master/src/constructors.jl) does the right thing if it is changed to accept a variable number of arguments
```julia
(::Type{NamedArray{T}}){T}(n...) = NamedArray(Array{T}(n...))
```

I am running Julia 0.5.1.

**Comment by davidavdav** [comment]
Thanks for pointing this out.  I hardly ever use such a constructor---or rather never, I suppose, or I would have noticed this.  I usually start with an existing array and then wrap things in a NamedArray.

**Comment by joelgoop** [comment]
Thank you! I'll probably use the other form from now on. I am still a Julia beginner and just started with NamedArrays today, so I haven't really learned the appropriate ways to do things. I was just a little confused when the readme example didn't work.

**Comment by davidavdav** [comment]
@nalimilan The offending syntax above `x = NamedArray{Int}(2, 2)` was introduced in d0b55df,  assume that this is the preferred way now in Julia?  

It took me a day to get my machine compile Julia again, after OS upgrades etc.  But I think it now finally accepts the `@compat` lines https://github.com/davidavdav/NamedArrays.jl/blob/master/src/namedarraytypes.jl#L35-L38 .
