### ISSUE TITLE
Customizing dimensions names

### ISSUE THREAD

**Issue by AntonioSaragga** [davidavdav/NamedArrays.jl#48]
First, would like to thank you for this very useful package! 

I am mostly working with  arrays in three dimensions and would like to change their names, lets say, from ``A, B, C`` to ``i, j, k`` Would this be possible?

**Comment by davidavdav** [comment]
Ehm, yes, in several ways, but the easiest is
```julia
x = rand(2, 2, 2)
n = NamedArray(x)
setdimnames!(n, ["i", "j", "k"])
```
You can also set the dimnames in the constructor, but then you need to also set the names of the indices as well.
