### ISSUE TITLE
name an 1-dim array

### ISSUE THREAD

**Issue by HenryLeongStat** [davidavdav/NamedArrays.jl#53]
Hello! Thank you for this useful package!
I try to name the 1-dim array in the constructor like the following:
`NamedArray([1,3,2,4],(["a","b","c","d"]))`
However, an error `Dimension mismatch` appears.
Is there any method that can name a 1-dim array in the constructor? Doesn't quite understand the example `indexing` in the documentation.

Thanks! 😄

**Comment by davidavdav** [comment]
Hi,

The 2nd argument in your call, `(["a","b","c","d"])` isn't parsed as a 1-tuple, but as a parenthesized expression.   You need to add a comma, as in `(["a","b","c","d"], )` or give an array-of-arrays: `[["a","b","c","d"]]`. 

Perhaps I should add a special constructor for 1-dim arrays.  That might make sense for typing, but might also be a bit confusing. 

Cheers

**Comment by HenryLeongStat** [comment]
It works! Thanks a lot! :D
