### ISSUE TITLE
Check get(io, :limit, true) in show

### ISSUE THREAD

**Issue by stevengj** [davidavdav/NamedArrays.jl#56]
Currently, the `show` method unconditionally checks `displaysize` in order to decide how much of the array to show.

It should probably check `limit = get(io, :limit, true)` ... if `limit == false`, then it should show the whole array.  (`:limit` is the documented `IOContext` property used to decide whether to show all of an array).

**Comment by davidavdav** [comment]
Great, just for testing, how get a handle to the `IO` object that represents the REPL?  I've never understood how the displaying of a REPL results ends up in the print/show chain.

**Comment by nalimilan** [comment]
Just use `STDOUT`.

**Comment by davidavdav** [comment]
on my REPL
```julia
a = randn(10,10)
a
show(STDOUT, a)
```
shows two different things, whereas 
```julia
n = NamedArray(a)
n
show(STDOUT, n)
```
shows the same.  But the current behaviour for NamedArrays is good enough to test with `IOContext(STDOUT, limit=false)`.

**Comment by nalimilan** [comment]
Ah, got it. I think the REPL uses something more or less like this: `IOContext(io, :limit => true, :displaysize => displaysize(STDOUT)`.

**Comment by stevengj** [comment]
The REPL only sets `:limit=>true`; it uses the default displaysize.  It also wraps `STDOUT` in a `Base.Terminals.TTYTerminal` object, which has more info about the terminal.
