### ISSUE TITLE
is there an easy way to convert NamedArray to Dict 

### ISSUE THREAD

**Issue by mandarup** [davidavdav/NamedArrays.jl#61]
This is how I am doing this now:
```
freqdict = Dict(name=> (namedarray)[name] 
                for name in names(namedarray)[1])
```

Question 1: is this the best way to achieve this

Question 2: Is this even necessary ..

**Comment by davidavdav** [comment]
A `FreqTable` can be multi-dimensional.  But if you're interested only in the case of a 1-dim contingency table, you could indeed write
```julia
Dict(n::NamedVector) = Dict(name => n[name] for name in names(n, 1))
```
But I don't really see the point---you can just access the freqtable `n` in the same way as the constructed Dict.

**Comment by mandarup** [comment]
@davidavdav  I needed to feed the dict to another function from another package which wouldn't accept the FreqTable type.

**Comment by davidavdav** [comment]
I've added the definition above in the code, so that in future releases this will be available.
