### ISSUE TITLE
Subset of NamedArray with duplicates

### ISSUE THREAD

**Issue by bkamins** [davidavdav/NamedArrays.jl#63]
Testing the new functionality.

Currently the following fails (it is unrelated to the changes):

```
julia> x = NamedArray([1 3; 2 4], ( ["a", "b"], ["c", "d"] ), ("Rows", "Cols"))
2×2 Named Array{Int64,2}
Rows ╲ Cols │ c  d
────────────┼─────
a           │ 1  3
b           │ 2  4

julia> x[["a","a"],:]
ERROR: Inconsistent dictionary sizes
```

and it is understandable why. @davidavdav But would you consider adding a more informative error message (just an idea - this is not crucial).

**Comment by davidavdav** [comment]
That looks like a bug to mee.

**Comment by bkamins** [comment]
Thanks!
