### ISSUE TITLE
Support for Julia-0.7

### ISSUE THREAD

**Issue by gpapo** [davidavdav/NamedArrays.jl#65]
Hello, I would be interested to know if the maintainers intend to update the Module to support the 0.7 version of Julia, with any help, or if continue to support Julia 0.5 has a clear precedence (in which case I would plan to create a new module directly).

**Comment by davidavdav** [comment]
I think I will not support 0.5 any more (so there is some most recent version of NamedArrays defined that will still work with 0.5), but I should start supporting 0.7.   And then I will no longer develop for 0.6 compatibility. 

Usually it takes quite some effort to get the module into shape for the next Julia.
