### ISSUE TITLE
unexpected prints with dot-fusion syntax

### ISSUE THREAD

**Issue by jtackm** [davidavdav/NamedArrays.jl#75]
```
x = NamedArray([0.1, 0.2, 0.3, 0.4, 0.5], (["A", "B", "C", "D", "E"],))
x .< 0.25
```

![image](https://user-images.githubusercontent.com/16350312/46137636-59842100-c24a-11e8-894c-701a50fa39cc.png)

I get these ```......``` + input array prints also when dot-comparing within functions. This is on Julia 1.0.0 and ```[86f7a689] NamedArrays v0.9.1```.

**Comment by davidavdav** [comment]
Yes, I see that there are some stray print statements in the code.  Must be a left over of trying to debug  broadcasting

**Comment by davidavdav** [comment]
Thanks, should be fixed in 8ab1e80135b64ef96cb5e83a375700b300957d8a .

**Comment by jtackm** [comment]
Can confirm issue solved on ```NamedArrays#master```, thanks for the quick check!

**Comment by diegozea** [comment]
@davidavdav Do you know why the 0.9.2 version isn't in METADATA?

**Comment by davidavdav** [comment]
Yes, I stull don't understand the process how to commit a new version https://github.com/JuliaLang/METADATA.jl/pull/18975
