### ISSUE TITLE
InvertedIndices.jl

### ISSUE THREAD

**Issue by bkamins** [davidavdav/NamedArrays.jl#77]
Have you considered using https://github.com/mbauman/InvertedIndices.jl for `Not` operation? It would be nice to have a common ancestor package. Otherwise we might get some namespace clashes.

**Comment by bkamins** [comment]
@davidavdav Following https://github.com/JuliaData/DataFrames.jl/issues/1825#issuecomment-498795026 would you consider to use `Not` form InvertedIndices.jl?

**Comment by davidavdav** [comment]
Would InvertedIndices.jl consider using `Not` from NamedArrays.jl?

I think this is a typical namespace clash, where we would both want to import `Not` from a hypothetical package `Thesaurus.jl` that defines identifiers and some semantic interpretation of the word.

**Comment by bkamins** [comment]
Yes - this is a typical problem 😞. Regarding which package should be the "source" you probably could consult @mbauman. My understanding is that InvertedIndices.jl is much lighter package that is providing only `Not` object so it is natural that NamedArrays.jl would depend on InvertedIndices.jl.

**Comment by nalimilan** [comment]
Yes, I agree NamedArrays should depend on InvertedIndices rather than the other way around, since InvertedIndices is small and basically only provides `Not`: it wouldn't make sense for it to depend on NamedArrays.

**Comment by davidavdav** [comment]
Your arguments make sense, of course.  I was just wondering...

**Comment by nalimilan** [comment]
Thanks!

**Comment by bkamins** [comment]
Thanks! Could you please tag a release?
