### ISSUE TITLE
When using sortslices(), the named rows do not follow the sorting.

### ISSUE THREAD

**Issue by tuckertranslator** [davidavdav/NamedArrays.jl#79]
So I made a named array, with rows and columns of type String. When I sort the array with sortslices(), the values are correctly rearranged but the NamedArray row names stay where they were so the values are no longer associated with the correct named row. 
Here is my code:
```
two_last = [] #initialize array to hold row names (type String)
for p in Iterators.product([1,3,7,9],[1,3,7,9]) #permutate all combos of length 2
    push!(two_last, p)
end

a = NamedArray(zeros(Int64,16,4)) #initialize named array
setnames!(a, string.(two_last), 1) #row names
setnames!(a, ["1", "3", "7", "9"], 2) #column names
 
for i in 1:size(a)[1] #fill named array
    a[i,:] = rand(Int8, 4)
end
display(a) #display for comparison

display(sortslices(a, dims = 1)) 
```
The two arrays have the same order of named rows, but the rows have different values; that is, the named rows do not change place along with their original values. 

The documentation for sortslices() can be found here: https://docs.julialang.org/en/v0.7.0/base/sort/
It is a Base function.

**Comment by davidavdav** [comment]
Ah well, sortslices is new to me, it looks like I need to overload that and sort the names, if that is at all possible.  I must say, that I don't really understand sortslices (how do two rows compare? by their first entry? Or is that what they mean by lexicographically).  At any rate, I need access to the underlying sort order.  I'd have to look into that.

**Comment by tuckertranslator** [comment]
Hi there. sortslices() sorts an array based on the values in a specified keyword dimension (keyword is 'dims'). For example, in a 2D array, sortslices(some_array, dims = 1) will sort by the leading value in each _row_. Does that make sense?

**Comment by davidavdav** [comment]
I think that for `ndims > 2` keeping names in the dimensions does not really make sense.  So I give a warning in that case.

**Comment by tuckertranslator** [comment]
Hi there. I think my array is only two dimensions.

**Comment by davidavdav** [comment]
Yes, but my code has to be general.  You code (with the commit above) should work.

**Comment by tuckertranslator** [comment]
Ahh now I understand. Thanks a lot.

**Comment by davidavdav** [comment]
Closing, as this seems to have been fixed a while ago
