### ISSUE TITLE
Slow compilation on Julia 1.3

### ISSUE THREAD

**Issue by Byrth** [davidavdav/NamedArrays.jl#81]
`using NamedArrays` on Julia 1.3 is slow to precompile and causes a 10 minute interpreter block after load on my computer.

I suspect this is due to the (re?)definition of AbstractDict signatures for Base functions. I'm not sure which, but I bet one of them actually exists and causes recompilation of large parts of base when redefined.

I ended up here after going down this rabbit hole: https://discourse.julialang.org/t/slowdown-after-package-load/33533 (computer info in link)

**Comment by davidavdav** [comment]
Thanks for spotting this.  I am sorry namedArrays caused you so much dismay... It is supposed to make life easier, instead.  From your work I can't see a clear solution, apart maybe from putting NamedArrays into Base, but that would go a bit far I suppose...

**Comment by Byrth** [comment]
No problem! I am still new to the language so it gave me some experience troubleshooting dependencies.

If I was going to continue further, I think that I'd probably try commenting out all of the AbstractDict definitions and then loading the package to see if it still caused massive input lag. If it didn't, I'd comment out half of them, load again, etc.

There may be only a few signatures that are causing the problem at the moment. If possible, though, the ideal would probably be to eliminate AbstractDict signatures from the package because who knows what the future holds for the Abstract type.

**Comment by nalimilan** [comment]
That's weird, as locally on 1.3 `using NamedArrays` is very fast (even including precompilation). This is worth reporting against Julia.

**Comment by davidavdav** [comment]
I just downloaded and built Julia 1.3.1 from source, which somehow went ridiculously fast (I think that all dependencies were already in place, which normally is not the case), but for me also `using NamedArrays` precompiles fast enough (a few seconds I suppose).

**Comment by Byrth** [comment]
Hmmm... I was loading it on v1.3.0 (and v1.3.1) and it was causing input lag. It appeared to load very quickly, but then would block the next command for >10 minutes.

I will try again today

**Comment by Byrth** [comment]
OK, looks like we have an intersection problem. 

Delete `.julia/compiled` |> `using CmdStan` @5.6.0 (no NamedArrays dependency) = precompiled and did not cause lag afterwards.
|> `using NamedArrays` = precompiled quickly but caused >10min of lag aftewards.
|> `exit()` |> julia |> `using NamedArrays` = loaded quickly and no lag afterwards.

I then went through CmdStan's dependencies and tested them pairwise prior to loading NamedArrays. It was the intersection of MCMCChains and NamedArrays that gave me trouble. The load order didn't matter. **Please let me know if you can replicate this.**

I went through MCMCChain's dependencies pairwise with NamedArrays and couldn't replicate the problem. Looking at MCMCChain's code, it looks like these are the most likely locations of conflict:
* constructors.jl, fileio.jl, MCMCChains.jl, modelchains.jl, summarise.jl, chains.jl

**Comment by nalimilan** [comment]
I'd report this against Julia. There have been other cases like this.

**Comment by Byrth** [comment]
Yes, this issue appears to have spread well beyond this package. I will close this now because it is incorrectly attributed.
